### ISSUE TITLE
 Delay Between Speed Detection and Loading Indicator Activation?

### ISSUE THREAD

**Issue by Marcus-Peterson** [limpkin/cdm324_fft#10]
Could you clarify how many seconds elapse from the detection of a speed value until the radar transitions back to the loading or processing indicator (the segment that moves around in circles)? I'm trying to understand the timing between displaying detected speeds and the return to the waiting/loading state.

I am talking specifically about the inbuilt display on the CDM 324

**Comment by limpkin** [comment]
Hello there!
The delay between sensing and speed display is 1/34.9 (see https://www.limpkin.fr/index.php?post/2022/03/31/CDM324-Doppler-Motion-Sensor-Backpack%2C-now-with-FFTs%21) = 28.6ms 
The animation is only displayed when no FFT peak is detected :)

**Comment by Marcus-Peterson** [comment]
Okey thanks!
