### ISSUE TITLE
STL or 3d print file for the printed case that holds the CDM324 and its backpack.

### ISSUE THREAD

**Issue by HAV0X1014** [limpkin/cdm324_fft#13]
I've looked around this repo and the other CDM324 backpack repo, and cannot find the specific STL file that the CDM324 radar listing on Tindie uses. I'd like this specific version as it appears to be stronger/thicker than the STL provided on the CDM324 backpack repo, actually fits the LCD and PCB used, and I'd like to see if I can add a cone onto the end to direct the "view" of the radar better. I'd also like it just because it looks nicer :)

Thank you for all of your work!

**Comment by limpkin** [comment]
oh I had forgotten about uploading it... thanks for reminding me :)
