### ISSUE TITLE
Please share some further infos about this project

### ISSUE THREAD

**Issue by will-code-for-pizza** [limpkin/cdm324_fft#2]
Hi Limpkin.fr

Please provide us beginners with some more infos about the CMD324 FFT:

* Fritzing.org breadboard cabeling example (f.e. for Arduino UNO R4 Wifi)
* Detailed information about the capabilities of onboard connectors shown in [THIS PICTURE](https://www.limpkin.fr/public/cdm324_v2/exp_pinout.png)
* An example Arduino sketch file, that shows, how to print out measured speed on serial console with high accuracy

Many thanks so far.
Have a nice day.

**Comment by limpkin** [comment]
Hello,
I'll try to get to it when I have the time.

**Comment by will-code-for-pizza** [comment]
Sorry, please don't get me wrong, but you sell your excellent product online without any detailed documentation. It would be nice for every of your customers to follow your developement cabling and Arduino code (which should exist due to your journey of building this backpack V2)

Please upload here and we will find the time to search into it for the needed information for our ongoing projects. 

Many thanks.

**Comment by limpkin** [comment]
Just to make sure I follow you, are you saying that https://www.limpkin.fr/index.php?post/2022/03/31/CDM324-Doppler-Motion-Sensor-Backpack%2C-now-with-FFTs%21 isn't detailed documentation?

I'm not sure to follow your reasoning: this CDM324 backpack is a **redesign** of its previous version. I therefore don't understand why it should carry its previous version legacy.

In any case, I've updated the readme at https://github.com/limpkin/cdm324_fft to provide basic instructions on how to get the speed through UART. That should hopefully unblock you

**Comment by will-code-for-pizza** [comment]
From a developer's perspective, things often seem simple because you had to go through them yourself during the development process, solve the problems and then put the problem aside.

As a customer, you are faced with the challenge of receiving a foreign device with which you have had no contact whatsoever.

I'm trying to illustrate my problem with your documentation (which from your point of view certainly seems extensive and complete) using an example.
The addition to your readme helped me a lot.
Thanks for that!

```
UART connection

To connect the device to an external platform through UART, please use the MCU UART RX/TX pins shown above.
The baud rate is 1Mbit/s, speed can be queried by sending the 'k' character for km/h or the 'm' character for mph.
```


Ok, I understand to connect MCU UART_RX to Arduino Pin 2 (RX) and MCU UART_TX to Arduino Pin 3 (TX).
(Whats about the "DOPPLER_OUT" ?)

I have to initialize the UART connection to 1MBit/s with 

`mySerial.begin(1000000);`

and send a "k" (ASCII char 107) to Arduino TX pin.

So, a simple code snippet should look like this:

```
#include <SoftwareSerial.h>

// Definieren Sie die Pins für TX und RX
const int RX_PIN = 2; // RX Pin
const int TX_PIN = 3; // TX Pin

SoftwareSerial mySerial(RX_PIN, TX_PIN); // Erstellen Sie das SoftwareSerial-Objekt

void setup() {
  mySerial.begin(1000000);
  Serial.begin(115200);

  delay(3000);
  Serial.println("Start");
}

void loop() {
    int bytesSent = mySerial.write(107);
    if (mySerial.available()) {
      String receivedData = mySerial.readString();
      Serial.println(receivedData);
      Serial.println(bytesSent);
    }
  delay(500);
}
```

The sketch produces weird output, even if the radar sensor does not register any movement

```
Start
%


!


�

�
!


```

I hope that this description is enough to describe the general handling problem.

Regards  ;-)

**Comment by limpkin** [comment]
Hello,

- the DOPPLER_OUT isn't part of the UART connection, which is why it is not documented in the UART connection paragraph
- as you're a developer, did you make sure that the Arduino board you're using can actually handle a 1Mbit/s baud rate?

**Comment by will-code-for-pizza** [comment]
Hi...

> as you're a developer, did you make sure that the Arduino board you're using can actually handle a 1Mbit/s baud rate?

I am using the newest Arduino UNO R4 Wifi, but you are right... It could be that the baud rate is too high for this device.
Could you please provide me with the hardware YOU are using for this ?

Otherwise:
Would it be possible to use DOPPLER_OUT to calculate the speed with the arduino ?
(If yes, how should I wire your CDM324 to the Arduino?)
As a reference I could use the measured speed on the LED display, so probably there is a workaround for this ?

Best!

Update:
The Arduino UNO R4 WiFi has a built-in ESP32-S3 module that enables wireless communication. The maximum baud rate typically supported by the UART interface of the ESP32-S3 module is 5 Mbit/s.

https://docs.arduino.cc/resources/datasheets/ABX00087-datasheet.pdf (page 10, PIN 3 + 5)

I am not sure, if I could use them for UART communication with the radar device and will give it a try also...

**Comment by limpkin** [comment]
> I am using the newest Arduino UNO R4 Wifi, but you are right... It could be that the baud rate is too high for this device.
Could you please provide me with the hardware YOU are using for this ?

I'm not using any hardware, as I've only been using the expansion board

> Would it be possible to use DOPPLER_OUT to calculate the speed with the arduino ?

yes, but that would involve basically doing everything that the on board MCU is already doing.

**Comment by will-code-for-pizza** [comment]
> yes, but that would involve basically doing everything that the on board MCU is already doing.

Except the amplification of the signal and accordingly the improved sensitivity of the CDM324, right ?


What would the wiring to an Arduino look like in this case?
Do the signals arrive at the Arduino analog or digital?

Is it also possible to operate the radar module with a different baud rate? (e.g. with 0.5 MBit/s)

Regards.

**Comment by limpkin** [comment]
> Except the amplification of the signal and accordingly the improved sensitivity of the CDM324, right ?

the MCU isn't doing any amplification, it's just running an FFT. DOPPLER_OUT is the signal going into the MCU ADC.
You'd therefore have to wire that signal to your board ADC.

As you're a developer, I'm sure you'll be able to recompile these source files to get a new baud rate.

**Comment by will-code-for-pizza** [comment]
Hi...

> yes, but that would involve basically doing everything that the on board MCU is already doing.

But I would at least benefit from the signal amplification. Right?
What would the wiring to the Arduino look like in this case?
Are the signals then digital or analog?


Is it also possible to operate the radar module with a different baud rate? (e.g. with 0.5 MBit/s)

Best!

**Comment by limpkin** [comment]
> But I would at least benefit from the signal amplification. Right?

correct.

> What would the wiring to the Arduino look like in this case?

connect that signal to your ADC input

> Are the signals then digital or analog?

analog, as extensively described in the website article

> Is it also possible to operate the radar module with a different baud rate? (e.g. with 0.5 MBit/s)

Yes, see my previous answer on that topic.

**Comment by will-code-for-pizza** [comment]
Sorry for the double post, my browser (Brave) goes crazy...  :-(   Thanks for the quick response.

**Comment by will-code-for-pizza** [comment]
> As you're a developer, I'm sure you'll be able to recompile these source files to get a new baud rate.

No, I am not a developer, I'm a normal person who wants to evaluate a radar signal with an Arduino and display it on a website.
I will try my best.

Maybe that explains all my questions. :-(



UPDATE:
https://github.com/limpkin/cdm324_fft/blob/main/fw/cdm324.ioc
USART2.BaudRate=1000000

**Comment by limpkin** [comment]
no: https://github.com/limpkin/cdm324_fft/blob/main/fw/Core/Src/user/debug.c#L81

**Comment by will-code-for-pizza** [comment]
Hi Mathieu, thanks for the hint/link.

I have decided to start from the very beginning and connected your CDM324 to my Raspberry Pi, which can handle up to 3 MBit/s UART.

Cabling:

```
CMD324                  <-->               < -->                 Raspberry Pi
=============================================================================
5V_IN                   external 5V HW-131 5V OUT
GND                     external 5V HW-131 GND
MCU UART_RX                                                      GPIO 15 (RXD)
MCU UART_TX                                                      GPIO 14 (TXD)
```
Reference:
https://www.limpkin.fr/public/cdm324_v2/exp_pinout.png
https://www.elektronik-kompendium.de/sites/raspberry-pi/fotos/raspberry-pi-15b.jpg

(UART connection was tested before on Raspberry Pi (TX/RX direct connection and sending/receiving strings))

The CDM324 measures speed from a computer fan with constant 14,6 mph.


In first terminal:
```
# cat /dev/ttyAMA0
```

In second terminal:
```
Set Baud rate:

# stty -F /dev/ttyAMA0 1000000

Check port setup:

# stty -F /dev/ttyAMA0
speed 1000000 baud; line = 0;
-brkint -imaxbel

Send 'k' to serial:

# echo "k" > /dev/ttyAMA0

or with line feed

# echo -e "k\r\n" > /dev/ttyAMA0

```

In first terminal only multiple empty lines or some lines with 'k' appear.
No string with any speed value.

Best.

**Comment by limpkin** [comment]
Similarly to our discussion about Arduino's, did you make sure the Rpi can actually handle 1mbit/s? is your wiring short enough?
[cdm324.zip](https://github.com/limpkin/cdm324_fft/files/12878987/cdm324.zip)
attached here is the firmware for a 57600 baud rate.
To flash it, you could use the stm32loader Python module, **only if you also purchased the expansion board with your sensor** https://pypi.org/project/stm32loader/
Command is: stm32loader -b 115200 -p  com_port -e -w -v -s -f F3 file.bin

otherwise, you'll need to do the reset/boot sequencing yourself.

**Comment by will-code-for-pizza** [comment]
Hi Mathieu,

as I wrote above, Raspi can handle up to 3 MBit/s (according to documentation, I haven't found any project, that uses so high baud rates...)

My wiring is very short. I am using 20cm breadboard cables with a direct connection from the module to Raspi.

I have purchased the expansion board and two sensors with LED.

Let's try the 57600 baud firmware. Many thanks for that! 


Update:

```
$ stm32loader -b 115200 -p /dev/ttyUSB0 -e -w -v -s -f F3 cdm324.bin 

Activating bootloader (select UART)
Bootloader activation timeout -- retrying
Bootloader version: 0x31
Chip id: 0x439 (STM32F301xx/302x4(6/8)/318xx)
Device UID: 0025-002F-5243570A-20313238
Flash size: 64 KiB
Extended erase (0x44), this can take ten seconds or more
Write 138 chunks at address 0x8000000...
Writing ████████████████████████████████ 138/138
Read 138 chunks at address 0x8000000...
Reading ████████████████████████████████ 138/138
Verification OK
```

**Comment by will-code-for-pizza** [comment]
By the way: 
Whats the correct command to store actual firmware from module to file ?

According to documentation:
https://pypi.org/project/stm32loader/


```
stm32loader -b 115200 -p /dev/ttyUSB0 -r -s -f F3 -a 0x8000000 -l 0x10000 cmd324_1mbit-baudrate.bin
```
generates a much bigger file. I will hope, it is restorable...

**Comment by limpkin** [comment]
I actually don't know, but I'm guessing it's documented...

**Comment by will-code-for-pizza** [comment]
Result with new 57600 firmware:

Same as here
https://github.com/limpkin/cdm324_fft/issues/2#issuecomment-1759123796

but after sending a few "k's", communication hangs up... 

```
root@radar:~# echo "k" > /dev/ttyAMA0
root@radar:~# echo "k" > /dev/ttyAMA0
root@radar:~# echo "k" > /dev/ttyAMA0
root@radar:~# echo "k" > /dev/ttyAMA0
root@radar:~# echo "k" > /dev/ttyAMA0
^[[A
```
:-(

(fresh rebooted Raspi, setting UART to 57600 --> ' stty -F /dev/ttyAMA0 57600 ')

**Comment by limpkin** [comment]
I'm guessing something is wrong with your setup... you're the third person flashing that custom firmware into this board, the two others managed to make it work. 
if you're using the expansion board, make sure that you're correctly setting the CTS/RTS signals: https://github.com/limpkin/cdm324_fft/blob/main/scripts/cdm324_device.py#L29

**Comment by will-code-for-pizza** [comment]
![IMG_20231012_120808](https://github.com/limpkin/cdm324_fft/assets/19435718/3d7a04b5-e8a2-4b00-9579-1b8f342e3993)
![IMG_20231012_120902](https://github.com/limpkin/cdm324_fft/assets/19435718/546b06fa-8009-4ece-ad3a-613239ec27f4)
![IMG_20231012_120914](https://github.com/limpkin/cdm324_fft/assets/19435718/15d9670b-73cf-4a29-8544-3ec754396eb8)
![IMG_20231012_120925](https://github.com/limpkin/cdm324_fft/assets/19435718/0d287cde-4a79-4f0b-9d80-af59acc85daa)

PS: On the picture, the module runs at 3V for a test... but I have changed it to 5V again.

PS2: Same result on Arduino UNO R4 Wifi

**Comment by will-code-for-pizza** [comment]
@limpkin Good morning :-)

Could it be that I have to pass the "k" to the module as RAW data? Just an idea...

https://klafyvel.me/blog/articles/fft-arduino/#dont_bother_with_communication_protocols_over_serial

**Comment by limpkin** [comment]
it depends on your library... at the end of the day you need to send 'k', which is the number 107 in ascii :)

**Comment by will-code-for-pizza** [comment]
Hi Mathieu, as you can see in all my code examples from Arduino to Raspberry, from a sketch to simple Bash commands, sending plain 'k' string or ASCII 127 to your module, with baud rates from 57600 to 1 MBit/s .... nothing happens. May I ask you, if you have ever tried this approach by yourself successfully?   Have a nice day. Regards.

**Comment by will-code-for-pizza** [comment]
Update with cdm324 FFT 57600 baud: (module shows 11 mph constantly)

UART testing sketch:

```
#include <Arduino.h>
#include <SoftwareSerial.h>

#define ARRAY_SIZE 10 // Size of array to store data
char receivedData[ARRAY_SIZE]; // Array to store data into
int dataCounter = 0; // Counter for received data



void setup() {
  // Init serial console baudrate
  Serial.begin(9600);
  
  // Init UART console baudrate
  Serial1.begin(57600);
  SoftwareSerial Serial1(0, 1); // RX, TX
}

void loop() {
  // Send string 'k' via UART
  Serial.println("Sending data...");
  Serial1.println("k");

  // Waiting for UART data
  if (Serial1.available()) {
    // Check if there is space left in array to store data
    while (dataCounter < ARRAY_SIZE) {
      Serial.println("Space left in array");
      char receivedChar = Serial1.read();
      receivedData[dataCounter] = receivedChar;
      dataCounter++;
    }

    int size = sizeof(receivedData);
    Serial.print("Array full. "); 
    Serial.print("Size:");
    Serial.println(size);

    for (int i = 0; i < ARRAY_SIZE; i++) {
      Serial.print(receivedData[i]);
    }
    Serial.println(); // New line
    // Reset counter
    dataCounter = 0;
  }
  delay(2000);
}
```

Result:

```
Sending data...
Sending data...
Sending data...
Sending data...
Sending data...
Sending data...
Space left in array
Space left in array
Space left in array
Space left in array
Space left in array
Space left in array
Space left in array
Space left in array
Space left in array
Space left in array
Array full. Size:10
����������
Sending data...
```
(If I disconnect the wires from the module, Arduino receives no data. So I guess, the received data comes definitely from the module UART TX)

It seems, that the data from the module was send with a big time delay.
For my understanding the data from module was transferred with an inappropriate baud rate, resulting in weird characters.
Array size is 10 and I received 10 chars in count, even though the module shows 11 mph speed (2 chars), so the amount of received chars should be 20 (?).


**The following questions arise for me:**
- How do I find the correct baud rate of the RX data so as not to get strange characters?
- Which string does the module return exactly when sending a 'k' ?
   (an example would be desirable, especially data length, parity bit, number of stop bits, and flow control settings)
- Do I have to/should I send several 'k's to the module to respond?
- How to use this method to take multiple measurements per second if the response from the module is (apparently) delayed?

**Comment by will-code-for-pizza** [comment]
Here is the sketch without unnessecary output to serial console with the same baud rate for console and UART.
Just to avoid UART communication issues.

```
#include <Arduino.h>
#include <SoftwareSerial.h>
#define ARRAY_SIZE 10 // Size of array to store data

char receivedData[ARRAY_SIZE]; // Array to store data into
int dataCounter = 0; // Counter for received data

bool debugMode = false;

void setup() {
  // Init serial console baudrate
  Serial.begin(57600);

  Serial.println("START");
  
  // Init UART console baudrate
  Serial1.begin(57600);
  SoftwareSerial Serial1(0, 1); // RX, TX

  while (!Serial) {
    ; // wait for serial port to connect. Needed for native USB port only
  }  
}

void loop() {
  // Send string 'k' via UART
  if (debugMode == true) {
    Serial.println("Sending data...");
  }
  Serial1.println('k');

  // Waiting for UART data
  if (Serial1.available()) {
    // Check if there is space left in array to store data
    while (dataCounter < ARRAY_SIZE) {
      if (debugMode) {
        Serial.println("Space left in array");
      }
      char receivedChar = Serial1.read();
      receivedData[dataCounter] = receivedChar;
      dataCounter++;
    }

    int size = sizeof(receivedData);
    if (debugMode) {
      Serial.print("Array full. "); 
      Serial.print("Size:");
      Serial.println(size);
    }

    for (int i = 0; i < ARRAY_SIZE; i++) {
      Serial.print(receivedData[i]);
    }
    Serial.println(); // New line
    // Reset counter
    dataCounter = 0;
  }
  delay(2000);
}
```
Result:


```
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������
����������

```

**Comment by will-code-for-pizza** [comment]
Update:

Issue with weird chars solved.  -->  Changed

`char receivedData[ARRAY_SIZE];`

to

`int receivedData[ARRAY_SIZE];`

Now output looks like this:

`-20-4-1-1-1-1-1-1-1-1`

I still investigate, why the values are not changing in case of turning computer fan ON or OFF....

**Comment by will-code-for-pizza** [comment]
Ok, now I need some more explanations:

```
const int bufferSize = 64;  // Max count of integer data
int dataBuffer[bufferSize];  // Buffer store
int bufferIndex = 0;  // actual index in buffer

void setup() {
  delay(3000);
  Serial.begin(57600);  // Start serial console
  Serial1.begin(57600); // Start UART

  // Send 'k' via UART TX
  Serial.println("Start");
  Serial1.println('k');
  Serial1.println('k');
  Serial1.println('k');
}

void loop() {

  Serial1.println('k');

  // Check for data via UART RX
  while (Serial1.available() > 0 && bufferIndex < bufferSize) {

    // !!!! We assume that the data are CHARACTER values !!!!!
    char receivedChar = Serial1.read();

    dataBuffer[bufferIndex] = receivedChar;  // read Integer-Wert
    bufferIndex++;  // increment buffer index
  }

  // Check for enough data
  if (bufferIndex >= bufferSize) {
    // Data output
    for (int i = 0; i < bufferIndex; i++) {
      Serial.print("Received: ");
      Serial.println(dataBuffer[i]);
    }

    // End Sketch
    while (true) {
      // just a loop
    }
  }
}
```

results in

```
Start
Received: -20
Received: -4
Received: -20
Received: -4
Received: -20
Received: -4
Received: -20
Received: -4
Received: -20
Received: -4
Received: -20
Received: -2
Received: -2
Received: -2
Received: -2
Received: -20
Received: -4
Received: -20
Received: -4
Received: -20
Received: -4
Received: -20
Received: -4
Received: -20
Received: -4
Received: -2
```

and 


```
const int bufferSize = 64;  // Max count of integer data
int dataBuffer[bufferSize];  // Buffer store
int bufferIndex = 0;  // actual index in buffer

void setup() {
  delay(3000);
  Serial.begin(57600);  // Start serial console
  Serial1.begin(57600); // Start UART

  // Send 'k' via UART TX
  Serial.println("Start");
  Serial1.println('k');
  Serial1.println('k');
  Serial1.println('k');
}

void loop() {

  Serial1.println('k');

  // Check for data via UART RX
  while (Serial1.available() > 0 && bufferIndex < bufferSize) {

    // !!!! We assume that the data are INTEGER values !!!!!
    int receivedChar = Serial1.read();

    dataBuffer[bufferIndex] = receivedChar;  // read Integer-Wert
    bufferIndex++;  // increment buffer index
  }

  // Check for enough data
  if (bufferIndex >= bufferSize) {
    // Data output
    for (int i = 0; i < bufferIndex; i++) {
      Serial.print("Received: ");
      Serial.println(dataBuffer[i]);
    }

    // End Sketch
    while (true) {
      // just a loop
    }
  }
}

```

results in


```
Start
Received: 236
Received: 252
Received: 236
Received: 252
Received: 236
Received: 252
Received: 236
Received: 252
Received: 236
Received: 252
Received: 236
Received: 254
Received: 254
Received: 254
Received: 252
Received: 236
Received: 252
Received: 236
Received: 252
Received: 236
Received: 252
Received: 236
```

None of the values have anything to do with measured speed.

:-(

**Comment by will-code-for-pizza** [comment]
There are also remaining questions about the moules DOPPLER_OUT...

Module shows 10.6 mph constantly

```
const int radarPin = A0; // Analog IN to CDM324-sensor DOPPLER_OUT

void setup() {
  Serial.begin(57600); // Start serial communication
}

void loop() {
  int sensorValue = analogRead(radarPin); // Read values from analog port
  Serial.println(sensorValue); // Print values
  delay(1000); 
}
```

Result:

```
923
0
399
896
997
110
0
888
685
859
0
0
894
980
0
0
891
689
0
0
0
1023
405
0
```

**Comment by limpkin** [comment]
one of my customers is also manually rebooting the CDM324 using the reset input (by driving it low for 100ms)... maybe you could do this too?

**Comment by will-code-for-pizza** [comment]
> one of my customers is also manually rebooting the CDM324 using the reset input (by driving it low for 100ms)... maybe you could do this too?

For sure I could do this:

```
const int resetPin = 4; // Digital pin connectet do modules nRESET

void setup() {
  pinMode(resetPin, OUTPUT);
  // Set PIN to LOW
  digitalWrite(resetPin, LOW);
  // Wait 10 ms
  delay(10);
  // Set PIN to HIGH
  digitalWrite(resetPin, HIGH);
}

void loop() {
  // just do it once
}
```

But it's not entirely clear to me at the moment how this could help me with my problems.
Especially because the module needs a few seconds after the reset to deliver values again.

Oh yes, of course during my tests I often switched the module OFF and ON while the UART communication was running in the sketch. Unfortunately without success/better values.

It would be very kind if you could also take a look at my questions at the end of the following post: (especially the 2nd one)
https://github.com/limpkin/cdm324_fft/issues/2#issuecomment-1764581752

**Comment by will-code-for-pizza** [comment]
Oh yes, I almost forgot... Can you please put the two firmwares for 57600 and 1MBit here in the GIT?

**Comment by limpkin** [comment]
I've added the bin files to the release tab.

> How do I find the correct baud rate of the RX data so as not to get strange characters?  

You should set the baud rate that matches the firmware you've flashed.

> Which string does the module return exactly when sending a 'k' ?

debug_printf("%d\r\n", speed);

> Do I have to/should I send several 'k's to the module to respond?

one char per query

> How to use this method to take multiple measurements per second if the response from the module is (apparently) delayed?

the response won't be delayed

I'm very sorry but there's so much I can help you with without actually digging into your personal code.  
I've had several other customers that managed to do what you're trying to do, I'll reach out to them to see if they're willing to share code.

**Comment by limpkin** [comment]
sample arduino code has been put on the readme, tested.

**Comment by will-code-for-pizza** [comment]
> sample arduino code has been put on the readme, tested.

Thanks for the arduino example
https://github.com/limpkin/cdm324_fft#sample-arduino-code-to-fetch-speed-from-device
but did you realize during your tests, that

- speed is only displayed once, then 0 once and then the output stops ?

```
07:18:11.885 -> Hello there!
07:18:11.917 -> Received from the CDM324:
07:18:11.917 -> CDM324 fw v0.1, compiled Oct  3 2023 16:11:55
07:18:11.917 -> 
07:18:11.950 -> 33.90
07:18:13.975 -> 0.00
```

- script crashes in 30% of cases ?

```
07:04:47.190 -> Firmware name: "/tmp/arduino/sketches/3FFDA1E6168788B49E3D5492DF3D250C/sketch_oct30a.ino", compiled on: Oct 30 2023
07:04:47.190 -> Fault on interrupt or bare metal(no OS) environment
07:04:47.222 -> ===== Thread stack information =====
07:04:47.222 ->   addr: 20007ed8    data: 000108b5
07:04:47.222 ->   addr: 20007edc    data: 40046f00
07:04:47.255 ->   addr: 20007ee0    data: 00000000
07:04:47.255 ->   addr: 20007ee4    data: 00009e67
07:04:47.255 ->   addr: 20007ee8    data: 000108b5
07:04:47.287 ->   addr: 20007eec    data: 0000421f
07:04:47.287 ->   addr: 20007ef0    data: 000108b5
07:04:47.287 ->   addr: 20007ef4    data: 000074c3
07:04:47.287 ->   addr: 20007ef8    data: 000074b9
07:04:47.287 ->   addr: 20007efc    data: 00002599
07:04:47.287 -> ====================================
07:04:47.287 -> =================== Registers information ====================
07:04:47.319 ->   R0 : 00000042  R1 : 40070120  R2 : 00000000  R3 : 00000000
07:04:47.319 ->   R12: ffffffff  LR : 000086a1  PC : 00009e00  PSR: 60000000
07:04:47.352 -> ==============================================================
07:04:47.352 -> Usage fault is caused by attempts to switch to an invalid state (e.g., ARM)
07:04:47.385 -> Show more call stack info by run: addr2line -e "/tmp/arduino/sketches/3FFDA1E6168788B49E3D5492DF3D250C/sketch_oct30a.ino".elf -a -f 00009e00 000086a0 00009e66 0000421e 000074c2 000074b8
```
The cause could be that in .arduino15/packages/arduino/hardware/renesas_uno/1.0.4/cores/arduino/Serial.cpp:114

```
  if(init_ok) {
    tx_done = false;
    R_SCI_UART_Write(&uart_ctrl, &c, 1);
    while (!tx_done) {}   //      <<<------ !!!
    return 1;
  }
```
more than one simultaneous access to the serial port should be attempted.
On Arduino, thats not allowed/possible.


At least the one-time output of the speed now works and the documentation is now better when it comes to Arduino.

Thanks a lot and keep grinding!

**Comment by limpkin** [comment]
It didn't crash for me, and you'll get 0 when no movement is detected.

**Comment by will-code-for-pizza** [comment]
Issue with crashing script was solved by removing external 5V power and connecting CDM324 5V to 5V Arduino pin.
*crazy*
