### ISSUE TITLE
dopplersensor display stuck at 0.4

### ISSUE THREAD

**Issue by Marcus-Peterson** [limpkin/cdm324_fft#5]
So, I have a voltage divider the delivers electricity to the dopplersensor, whenever I connect the 5v and GND to the mb102, the display shifts between a bunch of numbers (if I wave my hand in front of it for example). And after a couple of seconds it's stuck at 0.4, and sometimes all I can see is a segment go around in circles. 

I've tested to see if there was something wrong with the doppler sensor through the expansion board and connected it via usbc to my pc, but nothing. It seems fine..? It detects speeds flawlessly. 

When a/the segment goes around in circles it is incapable of detecting movements

What is going on here?

**Comment by limpkin** [comment]
hello,
Can you expand on " I have a voltage divider the delivers electricity to the dopplersensor"?
Is that the mb102 you're referring to? https://www.az-delivery.de/en/products/mb102-breadboard
could you send a picture of your wiring diagram?

**Comment by will-code-for-pizza** [comment]
I have a similar issue:

If I connect the CDM324 "standalone" via expansion board to USB 5V, measuring speed works fine.
Module detects movements and if nothing happened, the display shows circling line.

If I connect CDM324 to Arduino

```
CMD324   <----->   Arduino UNO R4 Wifi
=================================
nRESET             PIN 2 digital
5V_IN              5V (do NOT use external power supply or script will crash!)
GND                GND
MCU UART_RX        PIN 1 (TX)
MCU UART_TX        PIN 0 (RX)
```

display shows a constant speed ~ 4 km/h (range from 3.80 to 4.20 km/h)

(also with sample sketch from [HERE](https://github.com/limpkin/cdm324_fft))

**Comment by will-code-for-pizza** [comment]
Additional video from issue:

https://youtube.com/shorts/JUVHfLQQhDU

**Comment by limpkin** [comment]
@will-code-for-pizza your issue seems to be related to a noisy power supply, possibly injecting noise into the CDM324

**Comment by will-code-for-pizza** [comment]
> @will-code-for-pizza your issue seems to be related to a noisy power supply, possibly injecting noise into the CDM324

I shouldn't have bought that Chinese junk... (the power supply)    :-(
Thanks for the hint. I will try another one.
