### ISSUE TITLE
UART and 'k','u' commands & streaming data from CDM 324

### ISSUE THREAD

**Issue by Marcus-Peterson** [limpkin/cdm324_fft#6]
Quick question: 
When I send the 'k' to the doppler radar from let's say an MCU. Does my MCU only have to send it once and the data can be "streamed" or does the MCU need to send the 'k' command to get a new speed reading every time?

**Comment by limpkin** [comment]
the latter :)

**Comment by Marcus-Peterson** [comment]
Okay thanks. The reason I asked is because I can't seem to figure out how to actually stream data to my arduino:
`#include <Arduino.h>
#include <MKRWAN_v2.h>
#include <ArduinoJson.h>
#include "mkrwan_doppler_v3.h"

#define BUFFER_SIZE 64

uint8_t buffer[BUFFER_SIZE];
unsigned int bufferIndex = 0;
char command = UART_COMMAND; // 'k' for km/h, 'm' for mph

const String appEui = APP_EUI;
const String appKey = APP_KEY;
LoRaModem modem;

float realSpeedValue = -1.0; // Initialize to -1 to indicate no valid data yet

bool commandSent = false; // Added flag to track if the command has been sent

void setup() {
  Serial.begin(115200);
  while (!Serial);
  Serial1.begin(1000000);

  if (!modem.begin(EU868)) {
    Serial.println("Failed to start module");
    return;
  }

  Serial.println("Connecting via OTAA...");
  if (!modem.joinOTAA(appEui, appKey)) {
    Serial.println("OTAA connection failed");
    return;
  }
  Serial.println("OTAA successfully connected");
  sendCommandToRadar(); // This will send the initial command
}

void loop() {
  readRadarData();
  if (realSpeedValue > 0) {  // Check for positive, valid data
    sendLoRaMessage();
  }
}

void sendCommandToRadar() {
  if (!commandSent) {
    Serial1.write(command);
    Serial.println(String("Command '") + command + "' sent to radar.");
    commandSent = true;
  }
}

void processData() {
  if (bufferIndex < 1) return;
  
  char receivedString[BUFFER_SIZE + 1];
  strncpy(receivedString, (char*)buffer, bufferIndex);
  receivedString[bufferIndex] = '\0';
  Serial.print("Raw data received from radar: ");
  Serial.println(receivedString);
  
  if (isDigit(receivedString[0]) || receivedString[0] == '-') {
    float speedValue = atof(receivedString);
    if (speedValue > 0.0) {
      realSpeedValue = speedValue / 10.0;
      Serial.print("Interpreted speed value: ");
      Serial.println(realSpeedValue);
    }
  }
}

String JsonProcessor(float arg) {
  if (arg > 0.0) {
    StaticJsonDocument<200> doc;
    doc["kmh"] = arg;
    String output;
    serializeJson(doc, output);
    return output;
  }
  return "";
}

void readRadarData() {
  while (Serial1.available()) {
    buffer[bufferIndex++] = Serial1.read();
    if (bufferIndex == BUFFER_SIZE || !Serial1.available()) {
      processData();
      bufferIndex = 0; // Återställer bufferIndex för nästa läsning
    }
  }
}

void sendLoRaMessage() {
  static unsigned long lastSendTime = 0;
  if (millis() - lastSendTime > 10000 && realSpeedValue > 0.001) {
    String jsonData = JsonProcessor(realSpeedValue);
    if (!jsonData.isEmpty()) {
      modem.setPort(3);
      modem.beginPacket();
      modem.print(jsonData);
      int packetSuccess = modem.endPacket(true);
      if (packetSuccess > 0) {
        Serial.println("Message sent correctly: " + jsonData);
      } else {
        Serial.println("Error sending message! Error code: " + String(packetSuccess));
      }
      realSpeedValue = -1.0; // Möjliggör ny datauppdatering
    }
    lastSendTime = millis();
  }
}
`

**Comment by Marcus-Peterson** [comment]
So just to be clear, I'll have to send a new command (the 'k') to the radar everytime I want to get a speed reading?

**Comment by limpkin** [comment]
that's correct :)

**Comment by Marcus-Peterson** [comment]
@limpkin 
I understand that this issue is closed, but I believe it's better to continue the discussion here instead of opening a new issue for the same topic. Apologies if I'm repeating myself, but I want to ensure that I have a clear understanding of the communication process with the CDM 324.

As I understand it, the data from the CDM 324 cannot be continuously streamed to a device, such as a serial monitor. Instead, to obtain new speed-data values, the MCU must send a 'k' command each time it wants to read a new value. Could you confirm whether my understanding is correct?

For example, if I send the 'k' command once from the MCU, can I then set up some programmatic logic in, let's say an MCU and start a continuous streaming of speed-data values to a serial monitor? Or does each new data value require sending the command again, every time I want a new speed-data value? I ask because many applications using UART communication can continuously stream data. I'm a little confused trying to determine if this applies to the CDM 324 or if my current understanding of the way an MCU for example need to do, in order for it to collect a speed-data value (Ergo, it needs to send the 'k' command over and over to obtain new speed-data).

To clarify my question, here's a Python script demonstrating what I mean by data streaming over UART. Although I haven't tested this script, it should illustrate the concept:

```
import serial

# Set up UART communication parameters
uart = serial.Serial(port='/dev/ttyS1', baudrate=9600, bytesize=serial.EIGHTBITS, parity=serial.PARITY_NONE, stopbits=serial.STOPBITS_ONE)

# Transmit a data stream (example: sending a string continuously)
data = "Hello, UART streaming!"
uart.write(data.encode())  # Transmit data as bytes

# Receive a data stream (example: reading a buffer of 100 bytes)
received_data = uart.read(100)  # Read 100 bytes from UART

```

Can you confirm if the CDM 324 behaves like this, where it allows continuous streaming, or if each new data retrieval requires sending a new command? Your guidance would be greatly appreciated.

**Comment by Marcus-Peterson** [comment]
Also, How do I reopen issue? There is not button

**Comment by limpkin** [comment]
> such as a serial monitor. Instead, to obtain new speed-data values, the MCU must send a 'k' command each time it wants to read a new value. Could you confirm whether my understanding is correct?   

that is correct indeed :)   

> Or does each new data value require sending the command again, every time I want a new speed-data value   

that indeed

> Can you confirm if the CDM 324 behaves like this, where it allows continuous streaming, or if each new data retrieval requires sending a new command?

the latter

Tell you what, whenever I have time i'll try to code a streaming mode :)

**Comment by henridbr** [comment]
So I am not alone. This question seems obvious, but it's not.  
My first idea was that the sensor is sending a flow of data because the screen is always showing speed, but it's not the case. 
The sensor answers only when "k" is sent like the cop's handheld radar when he pushes on the  trigger. 
It is possible to add a presence detector (with an acute angle of detection) to do that.
Or by software to send "k" continuously in order to receive a flow of values and filter them to get useful data. 
Many problems I guess to discriminate different objects.

**Comment by Marcus-Peterson** [comment]
> So I am not alone. This question seems obvious, but it's not. My first idea was that the sensor is sending a flow of data because the screen is always showing speed, but it's not the case. The sensor answers only when "k" is sent like the cop's handheld radar when he pushes on the trigger. It is possible to add a presence detector (with an acute angle of detection) to do that. Or by software to send "k" continuously in order to receive a flow of values and filter them to get useful data. Many problems I guess to discriminate different objects.

Yes indeed, the only way I got, what you could consider a "stream" (It's not an actual stream, but it kind of looks like one). Is to just send a command to the radar every 600 milliseconds. 
But the problem with that is that it can cause problems later down the line once you want to say for example do counting and stuff like that. 

But yeah, I am less confused hope you are as well. 

Unless someone has any other thoughts or ideas, we can most likely close down this issue, again.

**Comment by Marcus-Peterson** [comment]
And also @limpkin I want to thank you personally for taking your time and answering all of the community's question. I appreciate this a lot. And I'm very grateful.

I'll make sure to contribute what I can to this FOS project. to make it easier for you.

**Comment by limpkin** [comment]
sure! let me know if you have any other question :)
