### ISSUE TITLE
Changing radius off CDM324

### ISSUE THREAD

**Issue by Marcus-Peterson** [limpkin/cdm324_fft#8]
Is it possible to programmatically change the circumference of the radius of the CDM324?

**Comment by limpkin** [comment]
do you mean its radiation pattern? that's something that is defined by its radiating elements

**Comment by Marcus-Peterson** [comment]
No, the detection radius of speed

**Comment by limpkin** [comment]
what do you mean by "radius"? do you mean "range"?

**Comment by Marcus-Peterson** [comment]
Well, the range of the actual cdm324 is some value, however. Detection is not in a straight line, that is why is was curious about the actual radius of the detection range. If I'm thinking about this correctly.

**Comment by limpkin** [comment]
I'm still confused... do you mean specify a sin(x) in case the object arrives at an angle?

**Comment by Marcus-Peterson** [comment]
Yeah, I guess so. I have no knowledge regarding the math. 
But I was thinking akin to this:
![image](https://github.com/limpkin/cdm324_fft/assets/73422974/4e271184-71ca-4a73-aa8d-c6b605d8631f)

**Comment by Marcus-Peterson** [comment]
Like for example, would I be able to change the detection radius as described in the image

**Comment by limpkin** [comment]
the drawing you made is of the radiation pattern, which can't be programmatically changed as it directly depends on the antenna design.
